import type {
  ArchitectureStyle,
  ProjectBlueprint,
} from "@ai-software-zoll/blueprint";

/**
 * Footer shared by every generated top-level doc. Extracted here (not
 * packages/templates) because a single reused string doesn't yet justify a
 * separate package/directory convention — revisit if packages/agents ever
 * needs the same text.
 */
export function renderFooter(blueprint: ProjectBlueprint): string {
  return `---\nGenerated by AI Software Zoll from Blueprint version ${blueprint.version}.\n`;
}

/**
 * Human-readable name for each architecture style, shared by
 * generate-architecture-md.ts (heading) and generate-agents-md.ts (a
 * one-line reference). The longer prose explanation of each style stays
 * local to generate-architecture-md.ts, the only consumer that needs it.
 */
export const ARCHITECTURE_STYLE_DISPLAY_NAMES: Record<ArchitectureStyle, string> = {
  modular: "Modular Architecture",
  layered: "Layered Architecture",
  "clean-architecture": "Clean Architecture",
  hexagonal: "Hexagonal Architecture",
  "domain-driven-design": "Domain-Driven Design",
};
