import type { ProjectBlueprint } from "@ai-software-zoll/blueprint";

/**
 * Footer shared by every generated top-level doc. Extracted here (not
 * packages/templates) because a single reused string doesn't yet justify a
 * separate package/directory convention — revisit if packages/agents ever
 * needs the same text.
 */
export function renderFooter(blueprint: ProjectBlueprint): string {
  return `---\nGenerated by AI Software Zoll from Blueprint version ${blueprint.version}.\n`;
}
