import type {
  ArchitectureStyle,
  ProjectBlueprint,
  Testing,
} from "@ai-software-zoll/blueprint";

/**
 * Footer shared by every generated top-level doc. Extracted here (not
 * packages/templates) because a single reused string doesn't yet justify a
 * separate package/directory convention — revisit if packages/agents ever
 * needs the same text.
 */
export function renderFooter(blueprint: ProjectBlueprint): string {
  return `---\nGenerated by AI Software Zoll from Blueprint version ${blueprint.version}.\n`;
}

/**
 * Human-readable name for each architecture style, shared by
 * generate-architecture-md.ts (heading) and generate-agents-md.ts (a
 * one-line reference). The longer prose explanation of each style stays
 * local to generate-architecture-md.ts, the only consumer that needs it.
 */
export const ARCHITECTURE_STYLE_DISPLAY_NAMES: Record<ArchitectureStyle, string> = {
  modular: "Modular Architecture",
  layered: "Layered Architecture",
  "clean-architecture": "Clean Architecture",
  hexagonal: "Hexagonal Architecture",
  "domain-driven-design": "Domain-Driven Design",
};

/**
 * Directive sentence describing which test types are required, derived from
 * the Blueprint's testing flags. Shared by generate-agents-md.ts and
 * generate-skills.ts's testing skill — both need the same "what's actually
 * required" statement, phrased for an AI agent to act on.
 */
export function renderTestingRequirements(testing: Testing): string {
  const required: string[] = [];
  if (testing.unit) required.push("unit tests");
  if (testing.integration) required.push("integration tests");
  if (testing.e2e) required.push("end-to-end (e2e) tests");

  if (required.length === 0) {
    return "No specific testing requirements are configured yet.";
  }

  return `New functionality must include ${required.join(", ")}.`;
}
