const MANAGED_START = "<!-- ai-zoll:managed:start -->";
const MANAGED_END = "<!-- ai-zoll:managed:end -->";

/**
 * Written once, immediately after MANAGED_END, when a file is first
 * created — never re-added afterward, even if the user deletes it. Purely a
 * one-time hint; the tool must not "fight" the user by restoring it.
 */
export const CUSTOM_ZONE_HINT =
  "<!-- Everything below this line is yours — ai-zoll will never modify or delete it on regeneration. -->";

export type MergeStatus = "created" | "regenerated" | "unrecognized";

export interface MergeResult {
  content: string;
  status: MergeStatus;
  /** Set only for "unrecognized" — distinguishes why the file was left alone. */
  detail?: string;
}

/**
 * Wraps generated content in the managed-region markers. The managed block
 * is always LF — matches the generator functions' template-literal output.
 * Whatever comes after this block (the file's "custom zone") is preserved
 * exactly as found on disk, whatever its line endings are; no normalization
 * is attempted (a documented limitation, not an oversight).
 */
export function wrapManaged(content: string): string {
  return `${MANAGED_START}\n${content}\n${MANAGED_END}\n`;
}

/**
 * A custom zone containing only the one-time hint comment (plus whitespace)
 * has no real user content — used to decide whether an orphaned file is
 * safe to delete outright.
 */
export function hasCustomContent(customZone: string): boolean {
  return customZone.split(CUSTOM_ZONE_HINT).join("").trim().length > 0;
}

/**
 * Finds the first MANAGED_START/MANAGED_END pair via plain indexOf — first
 * occurrence wins (deterministic even if a user pastes marker-like text
 * into their custom zone), and immune to CRLF issues since neither marker
 * contains an embedded newline. Returns null with a `detail` reason when
 * the markers can't be reliably located, distinguishing "never had markers
 * at all" (predates this mechanism, or was hand-written) from "markers
 * present but malformed" (edited inside the managed zone).
 */
export function extractCustomZone(
  existingContent: string,
): { customZone: string } | { customZone: null; detail: string } {
  const startIdx = existingContent.indexOf(MANAGED_START);
  const endIdx = existingContent.indexOf(MANAGED_END);

  if (startIdx === -1 && endIdx === -1) {
    return {
      customZone: null,
      detail: "no managed markers found (predates ai-zoll or was never generated by it)",
    };
  }
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    return {
      customZone: null,
      detail: "managed markers are malformed or incomplete",
    };
  }

  const afterEnd = existingContent.slice(endIdx + MANAGED_END.length);
  const customZone = afterEnd.startsWith("\n") ? afterEnd.slice(1) : afterEnd;
  return { customZone };
}

/**
 * The core merge: given a file's existing on-disk content (or undefined if
 * it doesn't exist yet) and freshly generated content, produces what should
 * be written. Never silently discards a custom zone it can't confidently
 * identify — status "unrecognized" means the caller must leave the file
 * untouched rather than write `content` (which is just the existing content
 * echoed back, for callers that want a uniform return shape).
 */
export function mergeManagedContent(
  existingContent: string | undefined,
  freshContent: string,
): MergeResult {
  if (existingContent === undefined) {
    return {
      content: wrapManaged(freshContent) + CUSTOM_ZONE_HINT + "\n",
      status: "created",
    };
  }

  const extracted = extractCustomZone(existingContent);
  if (extracted.customZone === null) {
    return { content: existingContent, status: "unrecognized", detail: extracted.detail };
  }

  return {
    content: wrapManaged(freshContent) + extracted.customZone,
    status: "regenerated",
  };
}
